# Generated by Django 4.0.2 on 2022-02-26 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents_D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('raw_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('date_check', models.BooleanField(default=False)),
                ('opinion', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=200)),
                ('del_yn', models.BooleanField(default=False)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='votes.competitions_m')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WinnerContents_D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateField()),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_content', to='votes.competitions_m')),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_content', to='contents.contents_d')),
                ('point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_content', to='votes.points_m')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_content', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes_H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('del_yn', models.BooleanField(default=False)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contents.contents_d')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
