# Generated by Django 4.0.2 on 2022-02-26 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0001_initial'),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contents_D',
            new_name='Contents_Detail',
        ),
        migrations.RenameModel(
            old_name='Likes_H',
            new_name='Likes_History',
        ),
        migrations.RenameModel(
            old_name='WinnerContents_D',
            new_name='WinnerContents_Detail',
        ),
    ]
