# Generated by Django 4.0.2 on 2022-02-27 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0002_rename_contents_d_contents_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes_history',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_history', to='contents.contents_detail'),
        ),
        migrations.AlterField(
            model_name='likes_history',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Likes_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_like', models.IntegerField()),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_master', to='contents.contents_detail')),
            ],
        ),
    ]
