# Generated by Django 4.0.2 on 2022-03-10 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0003_alter_likes_history_content_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('del_yn', models.BooleanField(default=False)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_master', to='contents.contents_detail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
