# Generated by Django 4.0.2 on 2022-02-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_rename_contents_d_contents_detail_and_more'),
        ('user', '0002_rename_userpoint_h_userpoint_history_and_more'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competitions_M',
            new_name='Competitions_Master',
        ),
        migrations.RenameModel(
            old_name='Points_M',
            new_name='Points_Master',
        ),
    ]
