# Generated by Django 4.0.2 on 2022-02-26 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPoint_H',
            new_name='UserPoint_History',
        ),
        migrations.RenameModel(
            old_name='UserPoint_M',
            new_name='UserPoint_Master',
        ),
        migrations.RenameModel(
            old_name='UserProfile_M',
            new_name='UserProfile_Master',
        ),
    ]
