# Generated by Django 4.0.2 on 2022-02-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpoint_history',
            old_name='received_at',
            new_name='change_date',
        ),
        migrations.RenameField(
            model_name='userpoint_history',
            old_name='amount_point',
            new_name='change_point',
        ),
    ]
