# Generated by Django 4.0.2 on 2022-03-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_received_at_userpoint_history_change_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile_master',
            name='nickname',
            field=models.CharField(default='초기 이름', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile_master',
            name='profile_img',
            field=models.ImageField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcktUwcoOIdHi8a2jA46S0p_tKU2iZ06Wt5Q&usqp=CAU', null=True, upload_to='profile_imgs'),
        ),
    ]
